spring.mongodb.uri=mongodb://localhost:27017/crash2cost
spring.mongodb.database=crash2cost

# Logging configuration
logging.file.name=logs/auth-service.log
logging.file.path=logs
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n
logging.level.root=INFO
logging.level.io.github.mrlevi1112=DEBUG